In [21]:
import pandas as pd
pd.set_option("display.max_columns", None)
pd.set_option('display.max_rows', 30)

In [12]:
df = pd.read_csv("Full-Dataset/processed/url_encoded_dataset.csv")
merged_df = pd.read_csv("Full-Dataset/processed/merged.csv").iloc[: , 1:]

C:\Users\ParkJaehyung\AppData\Local\Temp\ipykernel_21720\3731135304.py:1: DtypeWarning: Columns (3,6,10,17) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Full-Dataset/processed/url_encoded_dataset.csv")
C:\Users\ParkJaehyung\AppData\Local\Temp\ipykernel_21720\3731135304.py:2: DtypeWarning: Columns (5,8,15,39) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv("Full-Dataset/processed/merged.csv").iloc[: , 1:]

In [65]:
with open("Full-Dataset/processed/url_encoded_dataset.json", "w+") as f : 
    import json
    f.write(json.dumps(df.to_dict("records"), ensure_ascii=True, indent=2))

In [46]:
df.groupby(["tcp.flags"]).count()

,Unnamed: 0,ip.src_host,frame.time,http.request.uri.query,tcp.checksum,http.response,arp.src.proto_ipv4,http.content_length,Attack_type,http.request.full_uri,arp.dst.proto_ipv4,tcp.connection.rst,arp.hw.size,tcp.len,tcp.seq,tcp.options,tcp.connection.syn,http.referer,ip.dst_host,tcp.flags.ack,tcp.ack_raw,tcp.connection.fin,tcp.dstport,tcp.ack,http.file_data,tcp.connection.synack,tcp.payload,tcp.srcport,arp.opcode,0,GET,POST,TRACE,HTTP/1.0,HTTP/1.1,http.request.uri.scheme,http.request.uri.netloc,http.request.uri.path,http.request.uri.query.dict,http.file_data.dict
tcp.flags,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,737,737,737,0,737,737,737,737,737,737,737,737,737,737,737,737,737,737,737,737,737,737,737,737,737,737,737,737,737,737,737,737,737,737,737,0,0,737,737,737
0x00000002,1192,1192,1192,0,1192,1192,1192,1192,1192,1192,1192,1192,1192,1192,1192,1192,1192,1192,1192,1192,1192,1192,1192,1192,1192,1192,1192,1192,1192,1192,1192,1192,1192,1192,1192,0,0,1192,1192,1192
0x00000004,650,650,650,0,650,650,650,650,650,650,650,650,650,650,650,650,650,650,650,650,650,650,650,650,650,650,650,650,650,650,650,650,650,650,650,0,0,650,650,650
0x00000010,7202,7202,7202,0,7202,7202,7202,7202,7202,7202,7202,7202,7202,7202,7202,7202,7202,7202,7202,7202,7202,7202,7202,7202,7202,7202,7202,7202,7202,7202,7202,7202,7202,7202,7202,0,0,7202,7202,7202
0x00000011,2354,2354,2354,0,2354,2354,2354,2354,2354,2354,2354,2354,2354,2354,2354,2354,2354,2354,2354,2354,2354,2354,2354,2354,2354,2354,2354,2354,2354,2354,2354,2354,2354,2354,2354,0,0,2354,2354,2354
0x00000012,1221,1221,1221,0,1221,1221,1221,1221,1221,1221,1221,1221,1221,1221,1221,1221,1221,1221,1221,1221,1221,1221,1221,1221,1221,1221,1221,1221,1221,1221,1221,1221,1221,1221,1221,0,0,1221,1221,1221
0x00000018,79880,79880,79880,4379,79880,79880,79880,79880,79880,79880,79880,79880,79880,79880,79880,79880,79880,79880,79880,79880,79880,79880,79880,79880,79880,79880,79880,79880,79880,79880,79880,79880,79880,79880,79880,78697,78697,79880,79880,79880

In [4]:
df.head()

,Unnamed: 0,ip.src_host,frame.time,http.request.uri.query,tcp.checksum,http.response,arp.src.proto_ipv4,http.content_length,Attack_type,http.request.full_uri,arp.dst.proto_ipv4,tcp.connection.rst,arp.hw.size,tcp.len,tcp.seq,tcp.options,tcp.connection.syn,http.referer,ip.dst_host,tcp.flags.ack,tcp.ack_raw,tcp.connection.fin,tcp.dstport,tcp.flags,tcp.ack,http.file_data,tcp.connection.synack,tcp.payload,tcp.srcport,arp.opcode,0,GET,POST,TRACE,HTTP/1.0,HTTP/1.1,http.request.uri.scheme,http.request.uri.netloc,http.request.uri.path,http.request.uri.query.dict,http.file_data.dict
0,0,192.168.0.170,2021 01:45:35.974758000,NaN,0x0000016d,0.0,0,0.0,Password,http://192.168.0.128/DVWA/login.php,0,0.0,0.0,86.0,1.0,0101080a9a8a02a2d3a23932,0.0,0.0,192.168.0.128,1.0,2.788267e+09,0.0,80.0,0x00000018,1.0,0,0.0,474554202f445657412f6c6f67696e2e70687020485454...,37670.0,0.0,False,True,False,False,True,False,http,192.168.0.128,/DVWA/login.php,{},{'NaN': '0'}
1,1,192.168.0.170,2021 01:45:35.976362000,NaN,0x000067c9,0.0,0,0.0,Password,http://192.168.0.128/DVWA/login.php,0,0.0,0.0,86.0,1.0,0101080a9a8a02a3d3a23935,0.0,0.0,192.168.0.128,1.0,3.173240e+08,0.0,80.0,0x00000018,1.0,0,0.0,474554202f445657412f6c6f67696e2e70687020485454...,37672.0,0.0,False,True,False,False,True,False,http,192.168.0.128,/DVWA/login.php,{},{'NaN': '0'}
2,2,192.168.0.170,2021 01:45:36.094926000,NaN,0x000057a1,0.0,0,37.0,Password,http://192.168.0.128/DVWA/login.php,0,0.0,0.0,260.0,1.0,0101080a9a8a031bd3a239b3,0.0,0.0,192.168.0.128,1.0,9.393408e+08,0.0,80.0,0x00000018,1.0,username=admin&password=0&Login=Login,0.0,504f5354202f445657412f6c6f67696e2e706870204854...,37674.0,0.0,False,False,True,False,True,False,http,192.168.0.128,/DVWA/login.php,{},"{'username': 'admin', 'password': '0', 'Login'..."
3,3,192.168.0.170,2021 01:45:36.095802000,NaN,0x0000964a,0.0,0,38.0,Password,http://192.168.0.128/DVWA/login.php,0,0.0,0.0,261.0,1.0,0101080a9a8a031cd3a239b3,0.0,0.0,192.168.0.128,1.0,3.983958e+09,0.0,80.0,0x00000018,1.0,username=admin&password=00&Login=Login,0.0,504f5354202f445657412f6c6f67696e2e706870204854...,37676.0,0.0,False,False,True,False,True,False,http,192.168.0.128,/DVWA/login.php,{},"{'username': 'admin', 'password': '00', 'Login..."
4,4,192.168.0.170,2021 01:45:36.209790000,NaN,0x0000ce94,0.0,0,0.0,Password,http://192.168.0.128/DVWA/login.php,0,0.0,0.0,221.0,1.0,0101080a9a8a038ed3a23a26,0.0,0.0,192.168.0.128,1.0,6.664912e+08,0.0,80.0,0x00000018,1.0,0,0.0,474554202f445657412f6c6f67696e2e70687020485454...,37678.0,0.0,False,True,False,False,True,False,http,192.168.0.128,/DVWA/login.php,{},{'NaN': '0'}

In [23]:
merged_df.groupby(["Attack_type","http.data.value"]).count()

                                                                  ip.src_host
Attack_type   http.data.value
Password      0                                                         59194  \
              00                                                        11841
              Login                                                     23677
              admin                                                     23677
SQL_injection (SELECT (CASE WHEN (1003=4868) THEN 'Submitid=5...            1
...                                                                       ...
              Submitid=59;WAITFOR DELAY '0:0:5'--                           5
Uploading     0.0                                                        1907
XSS           0                                                         14768
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...          765
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...          382

                                                                  frame.time
Attack_type   http.data.value
Password      0                                                        59194  \
              00                                                       11841
              Login                                                    23677
              admin                                                    23677
SQL_injection (SELECT (CASE WHEN (1003=4868) THEN 'Submitid=5...           1
...                                                                      ...
              Submitid=59;WAITFOR DELAY '0:0:5'--                          5
Uploading     0.0                                                       1907
XSS           0                                                        14768
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...         765
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...         382

                                                                  tcp.checksum
Attack_type   http.data.value
Password      0                                                          59194  \
              00                                                         11841
              Login                                                      23677
              admin                                                      23677
SQL_injection (SELECT (CASE WHEN (1003=4868) THEN 'Submitid=5...             1
...                                                                        ...
              Submitid=59;WAITFOR DELAY '0:0:5'--                            5
Uploading     0.0                                                         1907
XSS           0                                                          14768
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...           765
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...           382

                                                                  http.response
Attack_type   http.data.value
Password      0                                                           59194  \
              00                                                          11841
              Login                                                       23677
              admin                                                       23677
SQL_injection (SELECT (CASE WHEN (1003=4868) THEN 'Submitid=5...              1
...                                                                         ...
              Submitid=59;WAITFOR DELAY '0:0:5'--                             5
Uploading     0.0                                                          1907
XSS           0                                                           14768
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...            765
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...            382

                                                                  arp.src.proto_ipv4
Attack_type   http.data.value
Password      0                                                                59194  \
              00                                                               11841
              Login                                                            23677
              admin                                                            23677
SQL_injection (SELECT (CASE WHEN (1003=4868) THEN 'Submitid=5...                   1
...                                                                              ...
              Submitid=59;WAITFOR DELAY '0:0:5'--                                  5
Uploading     0.0                                                               1907
XSS           0                                                                14768
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...                 765
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...                 382

                                                                  http.content_length
Attack_type   http.data.value
Password      0                                                                 59194  \
              00                                                                11841
              Login                                                             23677
              admin                                                             23677
SQL_injection (SELECT (CASE WHEN (1003=4868) THEN 'Submitid=5...                    1
...                                                                               ...
              Submitid=59;WAITFOR DELAY '0:0:5'--                                   5
Uploading     0.0                                                                1907
XSS           0                                                                 14768
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...                  765
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...                  382

                                                                  arp.dst.proto_ipv4
Attack_type   http.data.value
Password      0                                                                59194  \
              00                                                               11841
              Login                                                            23677
              admin                                                            23677
SQL_injection (SELECT (CASE WHEN (1003=4868) THEN 'Submitid=5...                   1
...                                                                              ...
              Submitid=59;WAITFOR DELAY '0:0:5'--                                  5
Uploading     0.0                                                               1907
XSS           0                                                                14768
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...                 765
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...                 382

                                                                  tcp.connection.rst
Attack_type   http.data.value
Password      0                                                                59194  \
              00                                                               11841
              Login                                                            23677
              admin                                                            23677
SQL_injection (SELECT (CASE WHEN (1003=4868) THEN 'Submitid=5...                   1
...                                                                              ...
              Submitid=59;WAITFOR DELAY '0:0:5'--                                  5
Uploading     0.0                                                               1907
XSS           0                                                                14768
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...                 765
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...                 382

                                                                  arp.hw.size
Attack_type   http.data.value
Password      0                                                         59194  \
              00                                                        11841
              Login                                                     23677
              admin                                                     23677
SQL_injection (SELECT (CASE WHEN (1003=4868) THEN 'Submitid=5...            1
...                                                                       ...
              Submitid=59;WAITFOR DELAY '0:0:5'--                           5
Uploading     0.0                                                        1907
XSS           0                                                         14768
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...          765
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...          382

                                                                  tcp.len
Attack_type   http.data.value
Password      0                                                     59194  \
              00                                                    11841
              Login                                                 23677
              admin                                                 23677
SQL_injection (SELECT (CASE WHEN (1003=4868) THEN 'Submitid=5...        1
...                                                                   ...
              Submitid=59;WAITFOR DELAY '0:0:5'--                       5
Uploading     0.0                                                    1907
XSS           0                                                     14768
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...      765
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...      382

                                                                  tcp.seq
Attack_type   http.data.value
Password      0                                                     59194  \
              00                                                    11841
              Login                                                 23677
              admin                                                 23677
SQL_injection (SELECT (CASE WHEN (1003=4868) THEN 'Submitid=5...        1
...                                                                   ...
              Submitid=59;WAITFOR DELAY '0:0:5'--                       5
Uploading     0.0                                                    1907
XSS           0                                                     14768
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...      765
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...      382

                                                                  tcp.options
Attack_type   http.data.value
Password      0                                                         59194  \
              00                                                        11841
              Login                                                     23677
              admin                                                     23677
SQL_injection (SELECT (CASE WHEN (1003=4868) THEN 'Submitid=5...            1
...                                                                       ...
              Submitid=59;WAITFOR DELAY '0:0:5'--                           5
Uploading     0.0                                                        1907
XSS           0                                                         14768
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...          765
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...          382

                                                                  tcp.connection.syn
Attack_type   http.data.value
Password      0                                                                59194  \
              00                                                               11841
              Login                                                            23677
              admin                                                            23677
SQL_injection (SELECT (CASE WHEN (1003=4868) THEN 'Submitid=5...                   1
...                                                                              ...
              Submitid=59;WAITFOR DELAY '0:0:5'--                                  5
Uploading     0.0                                                               1907
XSS           0                                                                14768
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...                 765
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...                 382

                                                                  http.referer
Attack_type   http.data.value
Password      0                                                          59194  \
              00                                                         11841
              Login                                                      23677
              admin                                                      23677
SQL_injection (SELECT (CASE WHEN (1003=4868) THEN 'Submitid=5...             1
...                                                                        ...
              Submitid=59;WAITFOR DELAY '0:0:5'--                            5
Uploading     0.0                                                         1907
XSS           0                                                          14768
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...           765
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...           382

                                                                  ip.dst_host
Attack_type   http.data.value
Password      0                                                         59194  \
              00                                                        11841
              Login                                                     23677
              admin                                                     23677
SQL_injection (SELECT (CASE WHEN (1003=4868) THEN 'Submitid=5...            1
...                                                                       ...
              Submitid=59;WAITFOR DELAY '0:0:5'--                           5
Uploading     0.0                                                        1907
XSS           0                                                         14768
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...          765
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...          382

                                                                  tcp.flags.ack
Attack_type   http.data.value
Password      0                                                           59194  \
              00                                                          11841
              Login                                                       23677
              admin                                                       23677
SQL_injection (SELECT (CASE WHEN (1003=4868) THEN 'Submitid=5...              1
...                                                                         ...
              Submitid=59;WAITFOR DELAY '0:0:5'--                             5
Uploading     0.0                                                          1907
XSS           0                                                           14768
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...            765
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...            382

                                                                  tcp.ack_raw
Attack_type   http.data.value
Password      0                                                         59194  \
              00                                                        11841
              Login                                                     23677
              admin                                                     23677
SQL_injection (SELECT (CASE WHEN (1003=4868) THEN 'Submitid=5...            1
...                                                                       ...
              Submitid=59;WAITFOR DELAY '0:0:5'--                           5
Uploading     0.0                                                        1907
XSS           0                                                         14768
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...          765
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...          382

                                                                  tcp.connection.fin
Attack_type   http.data.value
Password      0                                                                59194  \
              00                                                               11841
              Login                                                            23677
              admin                                                            23677
SQL_injection (SELECT (CASE WHEN (1003=4868) THEN 'Submitid=5...                   1
...                                                                              ...
              Submitid=59;WAITFOR DELAY '0:0:5'--                                  5
Uploading     0.0                                                               1907
XSS           0                                                                14768
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...                 765
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...                 382

                                                                  tcp.dstport
Attack_type   http.data.value
Password      0                                                         59194  \
              00                                                        11841
              Login                                                     23677
              admin                                                     23677
SQL_injection (SELECT (CASE WHEN (1003=4868) THEN 'Submitid=5...            1
...                                                                       ...
              Submitid=59;WAITFOR DELAY '0:0:5'--                           5
Uploading     0.0                                                        1907
XSS           0                                                         14768
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...          765
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...          382

                                                                  tcp.flags
Attack_type   http.data.value
Password      0                                                       59194  \
              00                                                      11841
              Login                                                   23677
              admin                                                   23677
SQL_injection (SELECT (CASE WHEN (1003=4868) THEN 'Submitid=5...          1
...                                                                     ...
              Submitid=59;WAITFOR DELAY '0:0:5'--                         5
Uploading     0.0                                                      1907
XSS           0                                                       14768
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...        765
              <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//E...        382

                                                                  tcp.ack
Attack_type   http.data.value

In [28]:
df.columns

Index(['Unnamed: 0', 'ip.src_host', 'frame.time', 'http.request.uri.query',
       'tcp.checksum', 'http.response', 'arp.src.proto_ipv4',
       'http.content_length', 'Attack_type', 'http.request.full_uri',
       'arp.dst.proto_ipv4', 'tcp.connection.rst', 'arp.hw.size', 'tcp.len',
       'tcp.seq', 'tcp.options', 'tcp.connection.syn', 'http.referer',
       'ip.dst_host', 'tcp.flags.ack', 'tcp.ack_raw', 'tcp.connection.fin',
       'tcp.dstport', 'tcp.flags', 'tcp.ack', 'http.file_data',
       'tcp.connection.synack', 'tcp.payload', 'tcp.srcport', 'arp.opcode',
       '0', 'GET', 'POST', 'TRACE', 'HTTP/1.0', 'HTTP/1.1',
       'http.request.uri.scheme', 'http.request.uri.netloc',
       'http.request.uri.path', 'http.request.uri.query.dict',
       'http.file_data.dict'],
      dtype='object')

In [153]:
float_able = []
float_unable = set(["Unnamed: 0", 'GET',
 'POST',
 'TRACE',
 'HTTP/1.0',
 'HTTP/1.1',
 '0',
 ])
for c in df.columns:
    if c in float_unable: continue
    try:
        try:
            if df[c].str.startswith("0x").astype("int").sum():
                df[c] = pd.Series(int(i,16) for i in df[c])
        except: pass
        df[c].astype("float")
    except Exception as e:
        # print(c, e) 
        float_unable.add(c)
print(all([(c in float_unable) for c in df.columns]))
float_able = [c for c in df.columns if c not in float_unable]

False

In [154]:
float_able

['tcp.checksum',
 'http.response',
 'http.content_length',
 'tcp.connection.rst',
 'arp.hw.size',
 'tcp.len',
 'tcp.seq',
 'tcp.connection.syn',
 'tcp.flags.ack',
 'tcp.ack_raw',
 'tcp.connection.fin',
 'tcp.dstport',
 'tcp.flags',
 'tcp.ack',
 'tcp.connection.synack',
 'tcp.srcport',
 'arp.opcode']

In [98]:
def debug_variable(c):
    print(c)
    return c

In [181]:
df.loc[(df["http.content_length"]+df["http.response"]) != 0][["http.content_length", "http.response"]]

       http.content_length  http.response
2                     37.0            0.0
3                     38.0            0.0
8                     37.0            0.0
9                     38.0            0.0
14                    37.0            0.0
...                    ...            ...
93177                277.0            1.0
93189                277.0            1.0
93202                303.0            1.0
93215                277.0            1.0
93227                277.0            1.0

[24824 rows x 2 columns]

In [156]:
temp = df.copy(True)
correlation = temp[[(c) for c in float_able if c not in ["ip.src_host", "ip.dst_host", "http"]]].corr("pearson")

In [157]:
correlation

,tcp.checksum,http.response,http.content_length,tcp.connection.rst,arp.hw.size,tcp.len,tcp.seq,tcp.connection.syn,tcp.flags.ack,tcp.ack_raw,tcp.connection.fin,tcp.dstport,tcp.flags,tcp.ack,tcp.connection.synack,tcp.srcport,arp.opcode
tcp.checksum,1.000000,0.002331,0.004428,-0.000770,-0.042884,0.016883,0.003261,0.000586,0.082131,0.021956,0.005549,0.004475,0.071601,0.009397,0.005118,0.035777,-0.040617
http.response,0.002331,1.000000,0.880912,-0.009351,-0.002808,0.270023,-0.026212,-0.012700,0.018824,0.009259,-0.017961,0.382570,0.039050,0.078556,-0.012856,-0.311477,-0.002660
http.content_length,0.004428,0.880912,1.000000,-0.031627,-0.009498,0.453693,-0.088654,-0.042956,0.063666,0.020076,-0.060750,0.270788,0.132074,-0.000736,-0.043482,-0.225236,-0.008996
tcp.connection.rst,-0.000770,-0.009351,-0.031627,1.000000,-0.002108,-0.124890,0.336144,-0.009535,-0.496774,-0.137580,-0.013485,0.252831,-0.365879,-0.022840,-0.009652,-0.201545,-0.001997
arp.hw.size,-0.042884,-0.002808,-0.009498,-0.002108,1.000000,-0.037507,-0.006159,-0.002864,-0.149192,-0.041318,-0.004050,-0.007251,-0.133619,-0.006859,-0.002899,-0.070360,0.947133
tcp.len,0.016883,0.270023,0.453693,-0.124890,-0.037507,1.000000,-0.335746,-0.169623,0.251402,0.066931,-0.239888,-0.240596,0.520824,-0.329840,-0.171701,0.123858,-0.035524
tcp.seq,0.003261,-0.026212,-0.088654,0.336144,-0.006159,-0.335746,1.000000,-0.027851,-0.139665,-0.034743,0.429257,0.585452,-0.413792,0.448975,-0.028193,-0.445862,-0.005833
tcp.connection.syn,0.000586,-0.012700,-0.042956,-0.009535,-0.002864,-0.169623,-0.027851,1.000000,-0.674707,-0.186858,-0.018315,-0.032186,-0.550604,-0.031021,-0.013109,0.095947,-0.002712
tcp.flags.ack,0.082131,0.018824,0.063666,-0.496774,-0.149192,0.251402,-0.139665,-0.674707,1.000000,0.276947,0.027145,-0.092335,0.818747,0.045977,0.019429,0.171296,-0.141305
tcp.ack_raw,0.021956,0.009259,0.020076,-0.137580,-0.041318,0.066931,-0.034743,-0.186858,0.276947,1.000000,0.010808,-0.019407,0.222575,0.016794,0.009769,0.041010,-0.039134
tcp.connection.fin,0.005549,-0.017961,-0.060750,-0.013485,-0.004050,-0.239888,0.429257,-0.018315,0.027145,0.010808,1.000000,0.260751,-0.209369,0.362256,-0.018539,-0.163942,-0.003836
tcp.dstport,0.004475,0.382570,0.270788,0.252831,-0.007251,-0.240596,0.585452,-0.032186,-0.092335,-0.019407,0.260751,1.000000,-0.378069,0.155441,0.396227,-0.789401,-0.006868
tcp.flags,0.071601,0.039050,0.132074,-0.365879,-0.133619,0.520824,-0.413792,-0.550604,0.818747,0.222575,-0.209369,-0.378069,1.000000,-0.342660,-0.122691,0.335883,-0.126555
tcp.ack,0.009397,0.078556,-0.000736,-0.022840,-0.006859,-0.329840,0.448975,-0.031021,0.045977,0.016794,0.362256,0.155441,-0.342660,1.000000,-0.030370,-0.010185,-0.006497
tcp.connection.synack,0.005118,-0.012856,-0.043482,-0.009652,-0.002899,-0.171701,-0.028193,-0.013109,0.019429,0.009769,-0.018539,0.396227,-0.122691,-0.030370,1.000000,-0.321492,-0.002745
tcp.srcport,0.035777,-0.311477,-0.225236,-0.201545,-0.070360,0.123858,-0.445862,0.095947,0.171296,0.041010,-0.163942,-0.789401,0.335883,-0.010185,-0.321492,1.000000,-0.066640
arp.opcode,-0.040617,-0.002660,-0.008996,-0.001997,0.947133,-0.035524,-0.005833,-0.002712,-0.141305,-0.039134,-0.003836,-0.006868,-0.126555,-0.006497,-0.002745,-0.066640,1.000000

In [158]:
correlation_crudential = set()
for col1 in correlation.columns:
    for col2 in correlation.columns:
        if col1 == col2: continue
        if correlation[col1][list(correlation.index).index(col2)] >= .2:
            correlation_crudential.add((col1, col2, correlation[col1][list(correlation.index).index(col2)]))

In [175]:
"""
arp.opcode : arp Operation Code : 요청이나 응답 패킷인지와 발생하는 주소 해결 유형을 정의
arp.hw.size : Hardware Address Length : 해당 패킷에 사용되는 물리 주소의 길이(byte)를 정의

tcp.len 
tcp.flags
tcp.flags.ack
tcp.seq
tcp.dstport

http.content_length : http response의 길이 (크기)
http.response : http response가 올바르게 도착하였는가 ( status == 200 을 의미)
"""
_ = [(a,b,c) for a,b,c in correlation_crudential if c >= .5]
_[:len(_)//2]

[('tcp.len', 'tcp.flags', 0.5208240442897379),
 ('tcp.flags.ack', 'tcp.flags', 0.818746529936385),
 ('arp.hw.size', 'arp.opcode', 0.9471332488530566),
 ('http.content_length', 'http.response', 0.8809118211298771),
 ('tcp.seq', 'tcp.dstport', 0.5854519019741504)]

In [159]:
available_columns = set()
for c1, c2, val in list(correlation_crudential):
    available_columns.add(c1)
    available_columns.add(c2)

In [160]:
available_columns # one by one correlation

{'arp.hw.size',
 'arp.opcode',
 'http.content_length',
 'http.response',
 'tcp.ack',
 'tcp.ack_raw',
 'tcp.connection.fin',
 'tcp.connection.rst',
 'tcp.connection.synack',
 'tcp.dstport',
 'tcp.flags',
 'tcp.flags.ack',
 'tcp.len',
 'tcp.seq',
 'tcp.srcport'}

In [126]:
new_df = pd.DataFrame()
for c1 in float_able:
    for c2 in float_able:
        if c1 == c2: continue
        if f"{c2}-{c1}" in new_df.columns: continue
        new_df[f"{c1}-{c2}"] = df[c1] + df[c2]

C:\Users\ParkJaehyung\AppData\Local\Temp\ipykernel_21720\1151983654.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[f"{c1}-{c2}"] = df[c1] + df[c2]
C:\Users\ParkJaehyung\AppData\Local\Temp\ipykernel_21720\1151983654.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[f"{c1}-{c2}"] = df[c1] + df[c2]
C:\Users\ParkJaehyung\AppData\Local\Temp\ipykernel_21720\1151983654.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[f"{c1}-{c2}"] = df[c1] + df[c2]
C:\Users\ParkJaehyung\AppData\Local\Temp\ipykernel_21720\1151983654.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[f"{c1}-{c2}"] = df[c1] + df[c2]
C:\Users\ParkJaehyung\AppData\Local\Temp\ipykernel_21720\1151983654.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_df[f"{c1}-{c2}"] = df[c1] + df[c2]

In [133]:
correlation = new_df.corr("pearson")

In [134]:
correlation_crudential = set()
for col1 in correlation.columns:
    for col2 in correlation.columns:
        if col1 == col2: continue
        if correlation[col1][list(correlation.index).index(col2)] >= .2:
            correlation_crudential.add((col1, col2, correlation[col1][list(correlation.index).index(col2)]))

In [138]:
available_columns = set()
for c1, c2, val in list(correlation_crudential):
    available_columns.add(c1)
    available_columns.add(c2)

available_columns_copy = set()
for element in available_columns:
    for c in element.split("-"):
        available_columns_copy.add(c)
available_columns = available_columns_copy
del available_columns_copy

In [139]:
available_columns

{'arp.hw.size',
 'arp.opcode',
 'http.content_length',
 'http.response',
 'tcp.ack',
 'tcp.ack_raw',
 'tcp.connection.fin',
 'tcp.connection.rst',
 'tcp.connection.syn',
 'tcp.connection.synack',
 'tcp.dstport',
 'tcp.flags.ack',
 'tcp.len',
 'tcp.seq',
 'tcp.srcport'}

In [140]:
float_unable

{'0',
 'Attack_type',
 'GET',
 'HTTP/1.0',
 'HTTP/1.1',
 'POST',
 'TRACE',
 'Unnamed: 0',
 'arp.dst.proto_ipv4',
 'arp.src.proto_ipv4',
 'frame.time',
 'http.file_data',
 'http.file_data.dict',
 'http.referer',
 'http.request.full_uri',
 'http.request.uri.netloc',
 'http.request.uri.path',
 'http.request.uri.query',
 'http.request.uri.query.dict',
 'http.request.uri.scheme',
 'ip.dst_host',
 'ip.src_host',
 'tcp.checksum',
 'tcp.flags',
 'tcp.options',
 'tcp.payload'}

In [142]:
df.head()

,Unnamed: 0,ip.src_host,frame.time,http.request.uri.query,tcp.checksum,http.response,arp.src.proto_ipv4,http.content_length,Attack_type,http.request.full_uri,arp.dst.proto_ipv4,tcp.connection.rst,arp.hw.size,tcp.len,tcp.seq,tcp.options,tcp.connection.syn,http.referer,ip.dst_host,tcp.flags.ack,tcp.ack_raw,tcp.connection.fin,tcp.dstport,tcp.flags,tcp.ack,http.file_data,tcp.connection.synack,tcp.payload,tcp.srcport,arp.opcode,0,GET,POST,TRACE,HTTP/1.0,HTTP/1.1,http.request.uri.scheme,http.request.uri.netloc,http.request.uri.path,http.request.uri.query.dict,http.file_data.dict
0,0,192.168.0.170,2021 01:45:35.974758000,NaN,0x0000016d,0.0,0,0.0,Password,http://192.168.0.128/DVWA/login.php,0,0.0,0.0,86.0,1.0,0101080a9a8a02a2d3a23932,0.0,0.0,192.168.0.128,1.0,2.788267e+09,0.0,80.0,0x00000018,1.0,0,0.0,474554202f445657412f6c6f67696e2e70687020485454...,37670.0,0.0,False,True,False,False,True,False,http,192.168.0.128,/DVWA/login.php,{},{'NaN': '0'}
1,1,192.168.0.170,2021 01:45:35.976362000,NaN,0x000067c9,0.0,0,0.0,Password,http://192.168.0.128/DVWA/login.php,0,0.0,0.0,86.0,1.0,0101080a9a8a02a3d3a23935,0.0,0.0,192.168.0.128,1.0,3.173240e+08,0.0,80.0,0x00000018,1.0,0,0.0,474554202f445657412f6c6f67696e2e70687020485454...,37672.0,0.0,False,True,False,False,True,False,http,192.168.0.128,/DVWA/login.php,{},{'NaN': '0'}
2,2,192.168.0.170,2021 01:45:36.094926000,NaN,0x000057a1,0.0,0,37.0,Password,http://192.168.0.128/DVWA/login.php,0,0.0,0.0,260.0,1.0,0101080a9a8a031bd3a239b3,0.0,0.0,192.168.0.128,1.0,9.393408e+08,0.0,80.0,0x00000018,1.0,username=admin&password=0&Login=Login,0.0,504f5354202f445657412f6c6f67696e2e706870204854...,37674.0,0.0,False,False,True,False,True,False,http,192.168.0.128,/DVWA/login.php,{},"{'username': 'admin', 'password': '0', 'Login'..."
3,3,192.168.0.170,2021 01:45:36.095802000,NaN,0x0000964a,0.0,0,38.0,Password,http://192.168.0.128/DVWA/login.php,0,0.0,0.0,261.0,1.0,0101080a9a8a031cd3a239b3,0.0,0.0,192.168.0.128,1.0,3.983958e+09,0.0,80.0,0x00000018,1.0,username=admin&password=00&Login=Login,0.0,504f5354202f445657412f6c6f67696e2e706870204854...,37676.0,0.0,False,False,True,False,True,False,http,192.168.0.128,/DVWA/login.php,{},"{'username': 'admin', 'password': '00', 'Login..."
4,4,192.168.0.170,2021 01:45:36.209790000,NaN,0x0000ce94,0.0,0,0.0,Password,http://192.168.0.128/DVWA/login.php,0,0.0,0.0,221.0,1.0,0101080a9a8a038ed3a23a26,0.0,0.0,192.168.0.128,1.0,6.664912e+08,0.0,80.0,0x00000018,1.0,0,0.0,474554202f445657412f6c6f67696e2e70687020485454...,37678.0,0.0,False,True,False,False,True,False,http,192.168.0.128,/DVWA/login.php,{},{'NaN': '0'}

In [5]:
%pip install tensorflow_datasets

Collecting tensorflow_datasetsNote: you may need to restart the kernel to use updated packages.

  Downloading tensorflow_datasets-4.9.2-py3-none-any.whl (5.4 MB)
     ---------------------------------------- 5.4/5.4 MB 9.8 MB/s eta 0:00:00
Requirement already satisfied: absl-py in c:\users\parkjaehyung\onedrive\바탕 화면\고려대학교\2학년 1학기\기계학습개론\ku-ml-endterm-project\myvenv\lib\site-packages (from tensorflow_datasets) (1.4.0)
Collecting array-record
  Downloading array_record-0.2.0-py310-none-any.whl (3.0 MB)
     ---------------------------------------- 3.0/3.0 MB 10.6 MB/s eta 0:00:00
Collecting click
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting dm-tree
  Downloading dm_tree-0.1.8-cp311-cp311-win_amd64.whl (101 kB)
     ---------------------------------------- 101.3/101.3 kB ? eta 0:00:00
Collecting etils[enp,epath]>=0.9.0
  Downloading etils-1.3.0-py3-none-any.whl (126 kB)
     -------------------------------------- 126.4/126.4 kB 7.3 MB/s eta 0:00:00
Requirement already satisfied: numpy in c:\users\parkjaehyung\onedrive\바탕 화면\고려대학교\2학년 1학기\기계학습개론\ku-ml-endterm-project\myvenv\lib\site-packages (from tensorflow_datasets) (1.23.5)
Collecting promise
  Using cached promise-2.3.tar.gz (19 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: protobuf>=3.20 in c:\users\parkjaehyung\onedrive\바탕 화면\고려대학교\2학년 1학기\기계학습개론\ku-ml-endterm-project\myvenv\lib\site-packages (from tensorflow_datasets) (4.22.4)
Requirement already satisfied: psutil in c:\users\parkjaehyung\onedrive\바탕 화면\고려대학교\2학년 1학기\기계학습개론\ku-ml-endterm-project\myvenv\lib\site-packages (from tensorflow_datasets) (5.9.5)
Requirement already satisfied: requests>=2.19.0 in c:\users\parkjaehyung\onedrive\바탕 화면\고려대학교\2학년 1학기\기계학습개론\ku-ml-endterm-project\myvenv\lib\site-packages (from tensorflow_datasets) (2.30.0)
Collecting tensorflow-metadata
  Downloading tensorflow_metadata-1.13.1-py3-none-any.whl (28 kB)
Requirement already satisfied: termcolor in c:\users\parkjaehyung\onedrive\바탕 화면\고려대학교\2학년 1학기\기계학습개론\ku-ml-endterm-project\myvenv\lib\site-packages (from tensorflow_datasets) (2.3.0)
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting tqdm
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
Requirement already satisfied: wrapt in c:\users\parkjaehyung\onedrive\바탕 화면\고려대학교\2학년 1학기\기계학습개론\ku-ml-endterm-project\myvenv\lib\site-packages (from tensorflow_datasets) (1.14.1)
Collecting importlib_resources
  Downloading importlib_resources-5.12.0-py3-none-any.whl (36 kB)
Requirement already satisfied: typing_extensions in c:\users\parkjaehyung\onedrive\바탕 화면\고려대학교\2학년 1학기\기계학습개론\ku-ml-endterm-project\myvenv\lib\site-packages (from etils[enp,epath]>=0.9.0->tensorflow_datasets) (4.5.0)
Collecting zipp
  Downloading zipp-3.15.0-py3-none-any.whl (6.8 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\parkjaehyung\onedrive\바탕 화면\고려대학교\2학년 1학기\기계학습개론\ku-ml-endterm-project\myvenv\lib\site-packages (from requests>=2.19.0->tensorflow_datasets) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\parkjaehyung\onedrive\바탕 화면\고려대학교\2학년 1학기\기계학습개론\ku-ml-endterm-project\myvenv\lib\site-packages (from requests>=2.19.0->tensorflow_datasets) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\parkjaehyung\onedrive\바탕 화면\고려대학교\2학년 1학기\기계학습개론\ku-ml-endterm-project\myvenv\lib\site-packages (from requests>=2.19.0->tensorflow_datasets) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\parkjaehyung\onedrive\바탕 화면\고려대학교\2학년 1학기\기계학습개론\ku-ml-endterm-project\myvenv\lib\site-packages (from requests>=2.19.0->tensorflow_datasets) (2022.12.7)
Requirement already satisfied: colorama in c:\users\parkjaehyung\onedrive\바탕 화면\고려대학교\2학년 1학기\기계학습개론\ku-ml-endterm-project\myvenv\lib\site-packages (from click->tensorflow_datasets) (0.4.6)
Requirement already satisfied: six in c:\users\parkjaehyung\onedrive\바탕 화면\고려대학교\2학년 1학기\기계학습개론\ku-ml-endterm-project\myvenv\lib\site-packages (from promise->tensorflow_datasets) (1.16.0)
Collecting googleapis-common-protos<2,>=1.52.0
  Downloading googleapis_common_protos-1.59.0-py2.py3-none-any.whl (223 kB)
     -------------------------------------- 223.6/223.6 kB 6.7 MB/s eta 0:00:00
Building wheels for collected packages: promise
  Building wheel for promise (setup.py): started
  Building wheel for promise (setup.py): finished with status 'done'
  Created wheel for promise: filename=promise-2.3-py3-none-any.whl size=21547 sha256=1e73b91998cceb3d8094a8564d7945910098314878f3d6c77f6d11c620645906
  Stored in directory: c:\users\parkjaehyung\appdata\local\pip\cache\wheels\74\05\89\d0909dd6ebad0a26f2b4dcb2499b1d65999c5b6ed416be7f85
Successfully built promise
Installing collected packages: dm-tree, zipp, tqdm, toml, promise, importlib_resources, googleapis-common-protos, etils, click, tensorflow-metadata, array-record, tensorflow_datasets
Successfully installed array-record-0.2.0 click-8.1.3 dm-tree-0.1.8 etils-1.3.0 googleapis-common-protos-1.59.0 importlib_resources-5.12.0 promise-2.3 tensorflow-metadata-1.13.1 tensorflow_datasets-4.9.2 toml-0.10.2 tqdm-4.65.0 zipp-3.15.0

[notice] A new release of pip available: 22.3 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
import os
import tensorflow as tf
from tensorboard.plugins import projector
import tensorflow_datasets as tfds

In [7]:

(train_data, test_data), info = tfds.load(
    "imdb_reviews/subwords8k",
    split=(tfds.Split.TRAIN, tfds.Split.TEST),
    with_info=True,
    as_supervised=True,
)
encoder = info.features["text"].encoder

# shuffle and pad the data.
train_batches = train_data.shuffle(1000).padded_batch(
    10, padded_shapes=((None,), ())
)
test_batches = test_data.shuffle(1000).padded_batch(
    10, padded_shapes=((None,), ())
)
train_batch, train_labels = next(iter(train_batches))

WARNING:absl:TFDS datasets with text encoding are deprecated and will be removed in a future version. Instead, you should use the plain text version and tokenize the text using `tensorflow_text` (See: https://www.tensorflow.org/tutorials/tensorflow_text/intro#tfdata_example)

Downloading and preparing dataset Unknown size (download: Unknown size, generated: Unknown size, total: Unknown size) to C:\Users\ParkJaehyung\tensorflow_datasets\imdb_reviews\subwords8k\1.0.0...

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Generating splits...:   0%|          | 0/3 [00:00<?, ? splits/s]

Generating train examples...: 0 examples [00:00, ? examples/s]

Shuffling C:\Users\ParkJaehyung\tensorflow_datasets\imdb_reviews\subwords8k\1.0.0.incomplete7ADNF5\imdb_review…

Generating test examples...: 0 examples [00:00, ? examples/s]

Shuffling C:\Users\ParkJaehyung\tensorflow_datasets\imdb_reviews\subwords8k\1.0.0.incomplete7ADNF5\imdb_review…

Generating unsupervised examples...: 0 examples [00:00, ? examples/s]

Shuffling C:\Users\ParkJaehyung\tensorflow_datasets\imdb_reviews\subwords8k\1.0.0.incomplete7ADNF5\imdb_review…

WARNING:absl:Dataset is using deprecated text encoder API which will be removed soon. Please use the plain_text version of the dataset and migrate to `tensorflow_text`.

Dataset imdb_reviews downloaded and prepared to C:\Users\ParkJaehyung\tensorflow_datasets\imdb_reviews\subwords8k\1.0.0. Subsequent calls will reuse this data.

In [8]:

# Create an embedding layer
embedding_dim = 16
embedding = tf.keras.layers.Embedding(encoder.vocab_size, embedding_dim)
# Train this embedding as part of a keras model
model = tf.keras.Sequential(
    [
        embedding, # The embedding layer should be the first layer in a model.
        tf.keras.layers.GlobalAveragePooling1D(),
        tf.keras.layers.Dense(16, activation="relu"),
        tf.keras.layers.Dense(1),
    ]
)

# Compile model
model.compile(
    optimizer="adam",
    loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
    metrics=["accuracy"],
)

# Train model
history = model.fit(
    train_batches, epochs=1, validation_data=test_batches, validation_steps=20
)

2500/2500 [==============================] - 15s 5ms/step - loss: 0.5119 - accuracy: 0.6917 - val_loss: 0.3854 - val_accuracy: 0.8350

In [25]:

# Set up a logs directory, so Tensorboard knows where to look for files
log_dir=os.path.join("logs", "imdb-example")

# Save Labels separately on a line-by-line manner.
with open(os.path.join(log_dir, 'metadata.tsv'), "w+", encoding='utf-8') as f:
    for subwords in encoder.subwords:
        f.write(f"{subwords}\n")
    # Fill in the rest of the labels with "unknown"
    for unknown in range(1, encoder.vocab_size - len(encoder.subwords)):
        f.write("unknown #{}\n".format(unknown))

In [33]:

# Save the weights we want to analyse as a variable. Note that the first
# value represents any unknown word, which is not in the metadata, so
# we will remove that value.
weights = tf.Variable(model.layers[0].get_weights()[0][1:])
# Create a checkpoint from embedding, the filename and key are
# name of the tensor.
checkpoint = tf.train.Checkpoint(embedding=weights)
checkpoint.save(os.path.join(os.getcwd(),log_dir, "embedding.ckpt"))

FailedPreconditionError: c:\Users\ParkJaehyung\OneDrive\바탕 화면\고려대학교\2학년 1학기\기계학습개론\KU-ML-EndTerm-project\logs\imdb-example is not a directory

In [ ]:

# Set up config
config = projector.ProjectorConfig()
embedding = config.embeddings.add()
# The name of the tensor will be suffixed by `/.ATTRIBUTES/VARIABLE_VALUE`
embedding.tensor_name = "embedding/.ATTRIBUTES/VARIABLE_VALUE"
embedding.metadata_path = 'metadata.tsv'
projector.visualize_embeddings(log_dir, config)

In [13]:
%tensorboard --logdir=logs/imdb-example/

UsageError: Line magic function `%` not found.